import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./DashboardWrapper";
import { QueryProvider } from "@/lib/React-Query/QueryProvider";





const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
        <DashboardWrapper>
      {children}
      </DashboardWrapper>
        </QueryProvider>
      
      
       
        </body>
    </html>
  );
}
